# This rule is not used by the project testcompany itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testcompany
    app.kubernetes.io/managed-by: kustomize
  name: demoapp-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - demoapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - demoapps/status
  verbs:
  - get
