# This rule is not used by the project testcompany itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testcompany
    app.kubernetes.io/managed-by: kustomize
  name: demoapp-admin-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - demoapps
  verbs:
  - '*'
- apiGroups:
  - apps.example.com
  resources:
  - demoapps/status
  verbs:
  - get
